wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.6
    t:
      1:
      - 3
      2:
      - 3
      4: 3.8.6
      5: 0.10.22
      8:
      - 4
      - 5
activation:
  desc: null
  value: tanh
batch_size:
  desc: null
  value: 32
eta:
  desc: null
  value: 0.001
initialization:
  desc: null
  value: random
n_epochs:
  desc: null
  value: 10
neurons_layer_1:
  desc: null
  value: 64
neurons_layer_2:
  desc: null
  value: 32
