wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.6
    t:
      1:
      - 3
      2:
      - 3
      4: 3.8.6
      5: 0.10.22
      8:
      - 4
      - 5
epochs:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.005
