wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.6
    t:
      1:
      - 3
      2:
      - 3
      4: 3.8.6
      5: 0.10.22
      8:
      - 4
      - 5
activation:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 32
batchsz:
  desc: null
  value: 16
epochs:
  desc: null
  value: 5
init:
  desc: null
  value: xavier
learning_rate:
  desc: null
  value: 0.001
n_epochs:
  desc: null
  value: 5
num_hidden_layers:
  desc: null
  value: 3
optimizer:
  desc: null
  value: nadam
